# Generated by Django 5.2.9 on 2025-12-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_number', models.CharField(max_length=20, verbose_name='رقم الهوية')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='جهة العمل')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('expired', 'Expired'), ('alert', 'Alert'), ('match', 'Match'), ('no_match', 'No Match'), ('error', 'Error')], default='normal', max_length=20, verbose_name='الحالة')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='نسبة التطابق')),
                ('violations', models.TextField(blank=True, null=True, verbose_name='المخالفات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='faces/', verbose_name='صورة الوجه')),
            ],
            options={
                'verbose_name': 'سجل تحقق',
                'verbose_name_plural': 'سجلات التحقق',
                'ordering': ['-created_at'],
            },
        ),
    ]
